#reference from lecture slide
#reference from k8s officail toturail
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels: 
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name:  MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name:  mysql-secret
              key: mysql-root-pwd
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc        
---

apiVersion: v1
kind: Service
metadata:
  name:  mysql-service
  labels:
    app: mysql
spec:
  type: LoadBalancer
  selector:
    app:  mysql
  ports:
  - protocol: TCP
    port:  3306
    targetPort:  3306
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
